### ISSUE TITLE
Issues with Material import statements for blocks that have materials already defined

### ISSUE THREAD

**Issue by Thomoski** [NerdyPuzzle/Blockstates-plugin-MCreator#1]
**Summary**
When adding blockstates to a block that has already been created and given a material (for example STONE) - the generated code from the blockstate adds a new import statement that causes an ambiguous reference to that material and causes failures in compilation.

**Specifics**
It seems that MCreator adds an import statement of 
`import net.minecraft.world.level.material.Material;`
When a blockstate is added, a second import statement of 
`import net.minecraft.client.resources.model.Material;` is also added.

![image](https://github.com/NerdyPuzzle/Blockstates-plugin-MCreator/assets/37102233/42509b4e-f06f-42d2-b187-3e8dcaeb5622)

This is then reference in the constructor for the block - `Material.STONE` (in my example)
![image](https://github.com/NerdyPuzzle/Blockstates-plugin-MCreator/assets/37102233/37071416-7867-4a88-bc1a-10b4d599b808)

This seems to causes ambiguity in the Material.STONE (or whatever material) reference, which is what causes the compliation failure

Tested in MCreator 2023.4 using Forge for 1.19.4 (45.2.0)
Plugin version 1.2.1

**Workaround**
It's easy to workaround by simply removing one of the two import statements, or simply making the reference more verbose, but is a little annoying to have to do and lock the entire element within MCreator

**Comment by NerdyPuzzle** [comment]
That's weird, the plugin does not add that import anywhere in its code? Have you tested this with multiple blocks?

**Comment by NerdyPuzzle** [comment]
Check that this doesn't also happen without the plugin. This could be a bug in MCreator itself.

**Comment by NerdyPuzzle** [comment]
This might be related to the blockstate element regenerating the code of the block it uses. I'll have to test this tomorrow.

**Comment by Thomoski** [comment]
Yeah, pretty sure it is the plugin, this is from a PR made after I added the new block, but before installing the plugin:
![image](https://github.com/NerdyPuzzle/Blockstates-plugin-MCreator/assets/37102233/894a0163-e4f0-4fbb-90c3-fd5c5f79038e)

There's just the one import statement

**Comment by Thomoski** [comment]
Also tested after removing the plugin - it seems that blocks that have been given an itemstate before by the plugin retain the issue, but new blocks are completely unaffected:

![image](https://github.com/NerdyPuzzle/Blockstates-plugin-MCreator/assets/37102233/768624ba-ac59-40d9-8b4d-346623a8f0b7)

I'm assuming I need to clear out some cache somewhere to fix this after removing the plugin, but it does strongly suggest that as the source of the issue

**Comment by Thomoski** [comment]
> This might be related to the blockstate element regenerating the code of the block it uses. I'll have to test this tomorrow.

No rush, it's simple to workaround, but might catch some more inexperienced guys out

**Comment by NerdyPuzzle** [comment]
Yeah, I just have to include the right import in the overriden block template

**Comment by NerdyPuzzle** [comment]
only seems to happen in 1.19.4, very weird behaviour, i'll just slap the import in the template and call it a day
