### ISSUE TITLE
Blockstate texture missing

### ISSUE THREAD

**Issue by BigBalakay** [NerdyPuzzle/Blockstates-plugin-MCreator#2]
When using a procedure to change a blockstate the texture will be missing. When using Minecraft textures I can edit the code to get the texture to show properly but I can not do the same for imported/created textures.

The first 2 attachments are what is added by default. 

![no texture](https://github.com/user-attachments/assets/af379b1e-9c8f-4aaf-8bba-6c3b22ba2991)

https://github.com/user-attachments/assets/54c26464-2d1d-4458-a0dc-699ce3e2621e

The following 2 are what I was able to achieve.

![yes texture](https://github.com/user-attachments/assets/bebcf3fd-896e-417a-b83a-ab6675fdd21b)

https://github.com/user-attachments/assets/d0902151-de86-4c3a-a955-1fc4f0a7fd67

**Comment by majkus522** [comment]
In the first blockstate you are trying to use minecraft texture but use your mod namespace.
![355014214-af379b1e-9c8f-4aaf-8bba-6c3b22ba2991](https://github.com/user-attachments/assets/ed9c5c36-5f6b-444f-9403-d334abda69c3)

**Comment by majkus522** [comment]
Or if you want use your mod textures just remove "minecraft:"
![355014214-af379b1e-9c8f-4aaf-8bba-6c3b22ba2991](https://github.com/user-attachments/assets/87b705c5-5d07-461c-b3de-861dba21272a)

**Comment by ManuFlosoYT** [comment]
Im on Blockstates v1.5.1 on MCreator 2024.3 on NeoForge 1.21.1 and Im having the exact same issue, I can fix it by locking the element and manually editing the texture path
