### ISSUE TITLE
appears to have broken in patch 2024.3.42716

### ISSUE THREAD

**Issue by 0xBl4nk** [NerdyPuzzle/Blockstates-plugin-MCreator#5]
When I updated to the new patch 2024.3.42716 it seems to have broken, when trying to edit the blockstates they don't open, and when creating a new one I can't add anything, it gets a buggy screen

**Comment by NerdyPuzzle** [comment]
I couldn't reproduce this. What version of the plugin are you using? Did you have multiple versions of the plugin loaded at once?

**Comment by friyes** [comment]
I could be misunderstanding but I think they're talking about this,

https://github.com/user-attachments/assets/41eeaf0c-a969-4d65-9dc4-4e894ca300c9

I hope I'm not just using the plugin wrong..

**Comment by NerdyPuzzle** [comment]
I don't know why this doesn't happen to me. I will try to find why this happens.

**Comment by NerdyPuzzle** [comment]
I tried again with a more recent version of 2024.3 and they decided to rename a line of code that broke everything. By bad for not catching this earlier.
